"""
Stub inference server for load-test dry runs.

Mimics the two upstream APIs the gateway calls — Ollama's /api/generate and
OpenRouter's /chat/completions — with randomized latency instead of real
model inference. Lets the load simulator exercise the full classifier ->
decision engine -> cache -> routing pipeline over real HTTP without
spending real OpenRouter tokens or requiring a local Ollama install.

Not part of the production application — only used by scripts/loadtest/.
"""

import asyncio
import json
import random
import time
from collections.abc import AsyncGenerator

from fastapi import FastAPI, Request
from fastapi.responses import StreamingResponse

app = FastAPI(title="LLM Stub (load-test only)")

# Rough shape of real-world latency: local GPU inference is faster and more
# consistent; cloud calls carry network + queueing overhead and a longer tail.
LOCAL_LATENCY_RANGE = (0.25, 0.90)
CLOUD_LATENCY_RANGE = (0.40, 1.60)
CLOUD_P99_SPIKE_CHANCE = 0.03
CLOUD_P99_SPIKE_RANGE = (2.5, 4.5)

# Streaming: modeled as a first-chunk (TTFT) delay plus a small per-token
# delay, sized so the total elapsed time for a full stream stays roughly
# comparable to the non-streaming latency envelope above.
LOCAL_FIRST_CHUNK_RANGE = (0.05, 0.30)
LOCAL_PER_TOKEN_RANGE = (0.01, 0.05)
CLOUD_FIRST_CHUNK_RANGE = (0.15, 0.50)
CLOUD_FIRST_CHUNK_SPIKE_RANGE = (1.5, 3.0)
CLOUD_PER_TOKEN_RANGE = (0.02, 0.08)

STUB_ANSWER = (
    "This is a synthetic response generated by the load-test stub server. "
    "It stands in for a real LLM completion so that routing, caching, and "
    "classification behaviour can be measured under concurrency without "
    "incurring real inference cost."
)


def _stub_chunks() -> list[str]:
    """Split the stub answer into word-sized streaming chunks."""
    words = STUB_ANSWER.split(" ")
    return [w + " " for w in words[:-1]] + [words[-1]]


@app.post("/api/generate")
async def ollama_generate(request: Request):
    body = await request.json()

    if body.get("stream"):
        return StreamingResponse(
            _ollama_stream(body.get("model", "stub-local")),
            media_type="application/x-ndjson",
        )

    start = time.perf_counter()
    await asyncio.sleep(random.uniform(*LOCAL_LATENCY_RANGE))
    return {
        "model": body.get("model", "stub-local"),
        "response": STUB_ANSWER,
        "done": True,
        "total_duration": int((time.perf_counter() - start) * 1e9),
    }


async def _ollama_stream(model: str) -> AsyncGenerator[str, None]:
    chunks = _stub_chunks()
    await asyncio.sleep(random.uniform(*LOCAL_FIRST_CHUNK_RANGE))
    for chunk in chunks:
        yield json.dumps({"model": model, "response": chunk, "done": False}) + "\n"
        await asyncio.sleep(random.uniform(*LOCAL_PER_TOKEN_RANGE))
    yield json.dumps({"model": model, "response": "", "done": True, "total_duration": 0}) + "\n"


@app.get("/api/tags")
async def ollama_tags():
    return {"models": [{"name": "stub-local"}]}


@app.post("/chat/completions")
async def openrouter_completions(request: Request):
    body = await request.json()

    if body.get("stream"):
        return StreamingResponse(
            _openrouter_stream(body.get("model", "stub-cloud")),
            media_type="text/event-stream",
        )

    if random.random() < CLOUD_P99_SPIKE_CHANCE:
        await asyncio.sleep(random.uniform(*CLOUD_P99_SPIKE_RANGE))
    else:
        await asyncio.sleep(random.uniform(*CLOUD_LATENCY_RANGE))
    return {
        "id": "stub-completion",
        "model": body.get("model", "stub-cloud"),
        "choices": [
            {
                "index": 0,
                "message": {"role": "assistant", "content": STUB_ANSWER},
                "finish_reason": "stop",
            }
        ],
    }


async def _openrouter_stream(model: str) -> AsyncGenerator[str, None]:
    chunks = _stub_chunks()
    first_chunk_delay = (
        random.uniform(*CLOUD_FIRST_CHUNK_SPIKE_RANGE)
        if random.random() < CLOUD_P99_SPIKE_CHANCE
        else random.uniform(*CLOUD_FIRST_CHUNK_RANGE)
    )
    await asyncio.sleep(first_chunk_delay)
    for chunk in chunks:
        payload = {
            "id": "stub-completion",
            "model": model,
            "choices": [{"index": 0, "delta": {"content": chunk}}],
        }
        yield f"data: {json.dumps(payload)}\n\n"
        await asyncio.sleep(random.uniform(*CLOUD_PER_TOKEN_RANGE))
    yield "data: [DONE]\n\n"


@app.get("/health")
async def health():
    return {"status": "ok"}
